Repository tryber/sd-010-b-project-delivery-app, pull requests merged in 2021-11, with the labels that each got.

#9 ESTRUTURA - Adicionanod instalaçoes front/back
  package-lock.json
Labels: :writing_hand: In-Development :writing_hand:

#11 [teste]
  front-end/src/App.js
Labels: :writing_hand: In-Development :writing_hand:

#13 [MAIN GROUP 8] [BACK] [FEAT] [SEQUELIZE-SETUP]
  back-end/src/database/migrations/20211110175520-create-users.js
  back-end/src/database/migrations/20211110180844-create-sales.js
  back-end/src/database/migrations/20211110181746-create-products.js
  back-end/src/database/migrations/20211110183336-create-sales-products.js
  back-end/src/database/models/Product.js
  back-end/src/database/models/Sale.js
  back-end/src/database/models/SalesProduct.js
  back-end/src/database/models/User.js
  front-end/package-lock.json
  front-end/package.json
  package-lock.json
Labels: :writing_hand: In-Development :writing_hand:

#3 [MAIN GROUP 14] Desenvolve msc
  back-end/package-lock.json
  back-end/src/api/app.js
  back-end/src/controllers/users.js
  back-end/src/database/migrations/.gitkeep
  back-end/src/database/migrations/20211109193212-create-products.js
  back-end/src/database/migrations/20211109201910-create-users.js
  back-end/src/database/migrations/20211109202332-create-sales.js
  back-end/src/database/migrations/20211109204814-create-sales-products.js
  back-end/src/database/models/products.js
  back-end/src/database/models/sales.js
  back-end/src/database/models/salesproducts.js
  back-end/src/database/models/users.js
  back-end/src/database/seeders/20211110173708-products.js
  back-end/src/database/seeders/20211110175840-users.js
  back-end/src/database/seeders/20211110180338-sales.js
  back-end/src/database/seeders/20211110180810-salesProducts.js
  back-end/src/models/users.js
  back-end/src/routes/index.js
  back-end/src/services/products.js
  back-end/src/services/users.js
Labels: enhancement

#12 [MAIN GROUP 5] [FEAT] [SEQUELIZE]
  back-end/package-lock.json
  back-end/src/api/app.js
  back-end/src/database/migrations/20211110185037-create-users.js
  back-end/src/database/migrations/20211110185811-create-sales.js
  back-end/src/database/migrations/20211110190202-create-products.js
  back-end/src/database/migrations/20211110190638-create-sales-products.js
  back-end/src/database/models/products.js
  back-end/src/database/models/sales.js
  back-end/src/database/models/salesproducts.js
  back-end/src/database/models/users.js
  front-end/package-lock.json
  package-lock.json
Labels: :writing_hand: In-Development :writing_hand:

#73 [MAIN GROUP 19] [BACKEND] [SEQUELIZE] [CONFIG]
  back-end/.eslintignore
  back-end/.sequelizerc
  back-end/comandosSequelize.txt
  back-end/src/database/migrations/20211109222912-create-user.js
  back-end/src/database/migrations/20211109222939-create-sale.js
  back-end/src/database/migrations/20211109222946-create-product.js
  back-end/src/database/migrations/20211109222947-create-sales-product.js
  back-end/src/database/seeders/20211110211316-products.js
  back-end/src/database/seeders/20211110211404-users.js
  back-end/src/database/seeders/20211110211408-sales.js
  back-end/src/database/seeders/20211110211415-products_sales.js
  back-end/src/models/index.js
  back-end/src/models/product.js
  back-end/src/models/sale.js
  back-end/src/models/salesproduct.js
  back-end/src/models/user.js
  front-end/public/images/antarctica_pilsen_300ml.jpg
  front-end/public/images/becks_330ml.jpg
  front-end/public/images/becks_600ml.jpg
  front-end/public/images/brahma_600ml.jpg
  front-end/public/images/brahma_duplo_malte_350ml.jpg
  front-end/public/images/da_mantiqueira_red_ale.jpg
  front-end/public/images/heineken_600ml.jpg
  front-end/public/images/skol_269ml.jpg
  front-end/public/images/skol_beats_senses_269ml.jpg
  front-end/public/images/skol_beats_senses_313ml.jpg
  front-end/public/images/skol_lata_350ml.jpg
  front-end/public/images/stella_artois_275ml.jpg
  package-lock.json
Labels: :writing_hand: In-Development :writing_hand:

#83 [MAIN GROUP 8] [FRONT] [FEAT] [GENERAL COMPONENTS]
  README.md
  front-end/src/components/NavBar.jsx
  front-end/src/components/ProductCard.jsx
  front-end/src/components/ProductTableListCard.jsx
  front-end/src/components/StatusProductCard.jsx
  front-end/src/components/UserTableListCard.jsx
Labels: code review :mag_right:

#78 Tela de login com formulário e rota configurada
  README.md
  back-end/package-lock.json
  back-end/src/controllers/products.js
  back-end/src/database/seeders/20211110173708-products.js
  back-end/src/database/seeders/20211110175840-users.js
  back-end/src/models/products.js
  back-end/src/routes/index.js
  back-end/src/services/products.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/Routes.jsx
  front-end/src/components/Button.jsx
  front-end/src/components/Input.jsx
  front-end/src/components/Layout/Header/Header.jsx
  front-end/src/components/Layout/Layout.jsx
  front-end/src/components/LoginForm.jsx
  front-end/src/components/NavBar.jsx
  front-end/src/index.js
  front-end/src/pages/Login.js
  front-end/src/styles/loginPage.css
  front-end/src/utils/RenderDefault.jsx
  front-end/src/utils/RenderWithNavbar.jsx
Labels: code review :mag_right:

#92 [ Main group 11 ] - Front end
  back-end/package-lock.json
  front-end/.eslintignore
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/components/ExampleButton/style.js
  front-end/src/components/cards/index.jsx
  front-end/src/components/cards/styles.js
  front-end/src/components/exemplo.txt
  front-end/src/components/navbar/index.jsx
  front-end/src/components/navbar/styles.js
  front-end/src/index.css
  front-end/src/index.js
  front-end/src/pages/Administrator/Management/index.jsx
  front-end/src/pages/Administrator/Management/style.js
  front-end/src/pages/Administrator/meexclua.txt
  front-end/src/pages/Client/Checkout/index.jsx
  front-end/src/pages/Client/Checkout/style.js
  front-end/src/pages/Client/MyRequests/index.jsx
  front-end/src/pages/Client/MyRequests/style.js
  front-end/src/pages/Client/OrderDetails/index.jsx
  front-end/src/pages/Client/OrderDetails/style.js
  front-end/src/pages/Client/Products/index.jsx
  front-end/src/pages/Client/Products/style.js
  front-end/src/pages/Common/Login/index.jsx
  front-end/src/pages/Common/Login/style.js
  front-end/src/pages/Common/Register/index.jsx
  front-end/src/pages/Common/Register/style.js
  front-end/src/pages/Salesman/OrderDetails/index.jsx
  front-end/src/pages/Salesman/OrderDetails/style.js
  front-end/src/pages/Salesman/Requests/index.jsx
  front-end/src/pages/Salesman/Requests/style.js
  front-end/src/pages/index.js
  front-end/src/reportWebVitals.js
  front-end/src/services/httpService.js
  front-end/src/services/login/apiRequestLogin.js
  front-end/src/services/products/customerProduct.js
  front-end/src/services/register/apiRequestRegister.js
  front-end/src/services/salesProducts/apiRequestSalesProduct.js
  package-lock.json
Labels: :writing_hand: In-Development :writing_hand:

#121 Tela de registro + rota + validação do form
  front-end/package-lock.json
  front-end/src/App.js
  front-end/src/components/RegisterForm.jsx
  front-end/src/pages/Login.js
  front-end/src/pages/Register.js
  package-lock.json
Labels: code review :mag_right:

#140 [X] Requisito 3
  front-end/src/components/EmailInput.jsx
  front-end/src/components/PasswordInput.jsx
  front-end/src/helpers/validation/index.js
  front-end/src/helpers/validation/validateEmail.js
  front-end/src/helpers/validation/validatePassword.js
  front-end/src/pages/Login.jsx
  front-end/src/store/index.js
Labels: code review :mag_right:

#119 [ Main Group 2 ] [ Feature ] [ Req11 Back End ]
  .editorconfig
  back-end/src/api/app.js
  back-end/src/api/server.js
  back-end/src/controllers/products.js
  back-end/src/database/migrations/20211109211655-create-user.js
  back-end/src/database/migrations/20211109212236-create-product.js
  back-end/src/database/migrations/20211109213001-create-sale.js
  back-end/src/database/migrations/20211109220134-create-sale-product.js
  back-end/src/database/models/product.js
  back-end/src/database/models/sale.js
  back-end/src/database/models/saleproduct.js
  back-end/src/services/products.js
Labels: code review :mag_right:

#135 [ Main Group 2 ] [ Feature ] [ Req11 Frontend ]
  front-end/.prettierignore
  front-end/.prettierrc.json
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/components/NavBar.jsx
  front-end/src/context/Context.jsx
  front-end/src/context/Provider.jsx
  front-end/src/index.js
Labels: :writing_hand: In-Development :writing_hand:, :writing_hand: Feature :writing_hand:

#176 [Main group 11] [refactoring login functions]
  back-end/package-lock.json
  back-end/package.json
  back-end/src/api/app.js
  back-end/src/app/controllers/loginController.js
  back-end/src/app/services/loginService.js
  back-end/src/middlewares/loginValidations.js
  back-end/src/routes/loginRouter.js
Labels: :writing_hand: In-Development :writing_hand:

#191 [Main-Group-11][Bug-Req-02]
  back-end/src/api/app.js
  back-end/src/app/controllers/userController.js
  back-end/src/app/services/loginService.js
  back-end/src/app/services/userService.js
  back-end/src/database/models/User.js
  back-end/src/routes/loginRouter.js
  back-end/src/routes/userRouter.js
  front-end/src/pages/Common/Login/index.jsx
Labels: bug

#192 [Main-group-11][Bug][API]
  back-end/src/app/controllers/loginController.js
  front-end/src/pages/Common/Login/index.jsx
  front-end/src/services/httpService.js
  front-end/src/services/login/apiRequestLogin.js
Labels: bug

#188 [Group 1][Feat Fluxo do Vendendor]
  back-end/package-lock.json
  back-end/src/api/app.js
  back-end/src/api/controllers/saleController.js
  back-end/src/api/controllers/saleProductController.js
  back-end/src/api/controllers/userController.js
  back-end/src/api/routers/index.js
  back-end/src/api/routers/productRouter.js
  back-end/src/api/routers/saleProductRouter.js
  back-end/src/api/routers/saleRouter.js
  back-end/src/api/routers/userRouter.js
  back-end/src/api/server.js
  back-end/src/api/services/saleProductService.js
  back-end/src/api/services/saleService.js
  back-end/src/api/services/userService.js
  back-end/src/api/socket/status.js
  back-end/src/database/migrations/20211109193309-create-sales.js
  back-end/src/database/migrations/20211109195913-create-sales-products.js
  back-end/src/database/models/product.js
  back-end/src/database/models/sale.js
  back-end/src/database/models/saleProduct.js
  back-end/src/database/seeders/20211110192426-users.js
  back-end/yarn.lock
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/components/deliveryDetails.js
  front-end/src/components/drinkCard.js
  front-end/src/components/navBar.js
  front-end/src/components/orderCheckout.js
  front-end/src/components/orderNavBar.js
  front-end/src/components/statusCard.js
  front-end/src/components/tableOrder.js
  front-end/src/components/tableOrderBody.js
  front-end/src/components/tableProducts.js
  front-end/src/context/provider.js
  front-end/src/pages/Checkout.js
  front-end/src/pages/CustomerDetailOrder.js
  front-end/src/pages/CustomerOrders.js
  front-end/src/pages/Login.js
  front-end/src/pages/Products.js
  front-end/src/pages/SellerDetailOrder.js
  front-end/src/pages/SellerOrders.js
  front-end/src/pages/index.js
  front-end/src/services/saleAPI.js
  front-end/src/services/saleProductsAPI.js
  front-end/src/services/userAPI.js
  front-end/src/utils/asynFunc/changeStatus.js
  front-end/src/utils/socket/socketClient.js
Labels: code review :mag_right:

#200 [Main-Group-11][Req-03]
  __tests__/end-to-end/01login.test.js
  back-end/src/app/controllers/loginController.js
  back-end/src/app/controllers/userController.js
  back-end/src/app/services/loginService.js
  back-end/src/app/services/userService.js
  back-end/src/app/services/utils/serialize.js
  back-end/src/middlewares/auth/tokenJWT.js
  back-end/src/middlewares/auth/validJWT.js
  back-end/src/routes/productRouter.js
  back-end/src/routes/userRouter.js
  front-end/src/pages/Common/Login/index.jsx
Labels: :writing_hand: Feature :writing_hand:

#150 [MAIN GROUP 14] Desenvolve Tela de Produtos
  __tests__/end-to-end/03customer_products.test.js
  back-end/package-lock.json
  back-end/public/antarctica_pilsen_300ml.jpg
  back-end/public/becks_330ml.jpg
  back-end/public/becks_600ml.jpg
  back-end/public/brahma_600ml.jpg
  back-end/public/brahma_duplo_malte_350ml.jpg
  back-end/public/da_mantiqueira_red_ale.jpg
  back-end/public/heineken_600ml.jpg
  back-end/public/images/antarctica_pilsen_300ml.jpg
  back-end/public/images/becks_330ml.jpg
  back-end/public/images/becks_600ml.jpg
  back-end/public/images/brahma_600ml.jpg
  back-end/public/images/brahma_duplo_malte_350ml.jpg
  back-end/public/images/da_mantiqueira_red_ale.jpg
  back-end/public/images/heineken_600ml.jpg
  back-end/public/images/skol_269ml.jpg
  back-end/public/images/skol_beats_senses_269ml.jpg
  back-end/public/images/skol_beats_senses_313ml.jpg
  back-end/public/images/skol_lata_350ml.jpg
  back-end/public/images/stella_artois_275ml.jpg
  back-end/public/skol_269ml.jpg
  back-end/public/skol_beats_senses_269ml.jpg
  back-end/public/skol_beats_senses_313ml.jpg
  back-end/public/skol_lata_350ml.jpg
  back-end/public/stella_artois_275ml.jpg
  back-end/src/api/app.js
  back-end/src/controllers/products.js
  back-end/src/models/products.js
  back-end/src/services/products.js
  front-end/package-lock.json
  front-end/src/App.js
  front-end/src/apis/products.jsx
  front-end/src/components/CartCard.jsx
  front-end/src/components/NavBar.jsx
  front-end/src/components/ProductCard.jsx
  front-end/src/components/ProductsList.jsx
  front-end/src/context/Context.js
  front-end/src/context/Provider.js
  front-end/src/index.js
  front-end/src/pages/Products.js
  front-end/src/styles/cartCard.css
  front-end/src/styles/productCard.css
  front-end/src/styles/productList.css
Labels: code review :mag_right:

#181 [ Main Group 2 ] [ Feat ] [ Req 12 FrontEnd ]
  front-end/src/App.js
  front-end/src/components/Card.jsx
  front-end/src/components/NavBar.jsx
  front-end/src/pages/Product.jsx
Labels: :writing_hand: In-Development :writing_hand:, :writing_hand: Feature :writing_hand:

#210 [Main-Group-11][Req-10]
  __tests__/end-to-end/01login.test.js
  back-end/src/app/controllers/loginController.js
  back-end/src/app/controllers/userController.js
  back-end/src/app/services/loginService.js
  back-end/src/app/services/userService.js
  back-end/src/middlewares/error.js
  front-end/src/App.js
  front-end/src/pages/Common/Home.jsx
  front-end/src/pages/Common/Login/index.jsx
  front-end/src/pages/Common/Register/index.jsx
  front-end/src/services/register/apiRequestRegister.js
Labels: :writing_hand: Feature :writing_hand:

#215 [Main-Group-11][Bug][Req10/Req09]
  back-end/src/app/services/userService.js
  back-end/src/middlewares/auth/tokenJWT.js
  front-end/src/pages/Common/Register/index.jsx
Labels: bug

#220 [ Main Group 2 ] [ Feat ] [ Req 5 Back End ]
  back-end/package-lock.json
  back-end/package.json
  back-end/src/middlewares/userMiddlewares.js
Labels: code review :mag_right:

#138 [MAIN GROUP 9] [FRONT] [FEAT] [LOGIN SCREEN]
  front-end/src/App.css
  front-end/src/common/pages/Login.jsx
  front-end/src/components/RegisterComponents/RedirectToRegister.jsx
  front-end/src/index.css
  front-end/src/styles/login.css
Labels: code review :mag_right:

#243 [Main-Group-11][Req14][Route-Product]
  back-end/src/api/app.js
  back-end/src/app/controllers/loginController.js
  back-end/src/app/controllers/productController.js
  back-end/src/app/services/productService.js
  back-end/src/app/services/utils/serialize.js
  back-end/src/database/models/Product.js
  back-end/src/routes/index.js
  back-end/src/routes/productRouter.js
Labels: :writing_hand: Feature :writing_hand:

#229 [ Main Group 2 ] [ Feature ] [ Front ] [ Register ]
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/context/Provider.jsx
  front-end/src/pages/Login.jsx
  front-end/src/pages/Register.jsx
Labels: :writing_hand: In-Development :writing_hand:, :writing_hand: Feature :writing_hand:

#255 [ Main Group 2 ] [ Feature ] [ Front ] [ Requisito 8 ]
  front-end/src/pages/Register.jsx
Labels: :writing_hand: In-Development :writing_hand:, :writing_hand: Feature :writing_hand:

#261 [ Main Group 2 ] [ Feature ] [ Front ] [ Req 8 ]
  front-end/src/App.js
  front-end/src/pages/Register.jsx
Labels: :writing_hand: In-Development :writing_hand:, :writing_hand: Feature :writing_hand:

#257 [MAIN GROUP 6] [Data-testid dict]
  front-end/src/utils/dataTestIdDict.js
Labels: code review :mag_right:

#260 [MAIN GROUP 5] - Login
  back-end/package-lock.json
  back-end/package.json
  back-end/src/api/app.js
  back-end/src/controllers/Login.js
  back-end/src/database/migrations/20211110185811-create-sales.js
  back-end/src/database/migrations/20211110190202-create-products.js
  back-end/src/database/models/sales.js
  back-end/src/database/models/salesproducts.js
  back-end/src/database/models/users.js
  back-end/src/database/seeders/20211112185442-users.js
  back-end/src/database/seeders/20211112193354-products.js
  back-end/src/services/Login.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/index.css
  front-end/src/index.js
  front-end/src/pages/login.jsx
  front-end/src/routes/routes.js
Labels: code review :mag_right:

#143 [MAIN GROUP 8][FEAT][CUSTOMER CHECKOUT]
  back-end/package.json
  back-end/src/api/app.js
  back-end/src/api/server.js
  back-end/src/controllers/saleController.js
  back-end/src/database/controllers/userController.js
  back-end/src/database/migrations/20211110183336-create-sales-products.js
  back-end/src/database/migrations/20211116182852-modify_sales_status_column.js
  back-end/src/helpers/errorFunctions.js
  back-end/src/helpers/errorObjects.js
  back-end/src/helpers/helperFunctions.js
  back-end/src/middlewares/error.js
  back-end/src/routers/saleRouter.js
  back-end/src/services/productService.js
  back-end/src/services/saleService.js
  back-end/src/services/userService.js
  back-end/src/tests/salesPost.test.js
  back-end/src/tests/utils/constants.js
  back-end/src/utils/constants.js
  back-end/src/validations/saleValidation.js
  front-end/src/App.js
  front-end/src/components/CartForm.jsx
  front-end/src/components/NavBar.jsx
  front-end/src/components/ProductTableHeader.jsx
  front-end/src/components/ProductTableListCard.jsx
  front-end/src/context/Products/ProductsProvider.js
  front-end/src/context/Users/UsersProvider.js
  front-end/src/pages/CustomerCheckout.jsx
  front-end/src/services/APICalls.js
  front-end/src/tests/customerCheckout.test.js
  front-end/src/tests/renderWithRouter.js
  front-end/src/tests/utils/constants.js
  front-end/src/utils/allowanceToRender.js
Labels: :writing_hand: In-Development :writing_hand:, code review :mag_right:

#267 [MAIN GROUP 9] [LOGIN] [INVALID LOGIN] [NOT FOUND]
  back-end/src/routes/loginRouter.js
  back-end/src/service/login.js
  front-end/src/common/pages/Login.jsx
Labels: :writing_hand: In-Development :writing_hand:

#298 [Main Group 5][feat][Register][Def]
  back-end/src/database/services/userServices.js
  front-end/src/components/Register/registerComponent.jsx
  front-end/src/pages/login.jsx
Labels: :writing_hand: In-Development :writing_hand:

#315 [Main-Group-11] [Req-39]
  back-end/src/api/app.js
  back-end/src/app/controllers/productController.js
  back-end/src/app/controllers/salesProductController.js
  back-end/src/app/controllers/userController.js
  back-end/src/app/services/productService.js
  back-end/src/app/services/salesProductService.js
  back-end/src/app/services/utils/serialize.js
  back-end/src/database/migrations/20211110210003-salesProducts.js
  back-end/src/database/models/SalesProduct.js
  back-end/src/database/seeders/20211118042844-salesProducts.js
  back-end/src/routes/SalesProductRouter.js
  back-end/src/routes/index.js
  back-end/src/routes/userRouter.js
  front-end/src/App.js
  front-end/src/components/TableDetails/index.js
  front-end/src/components/TableDetails/style.js
  front-end/src/pages/Administrator/Management/index.jsx
  front-end/src/pages/Client/Details/index.jsx
  front-end/src/pages/Client/Details/style.js
  front-end/src/pages/Common/Login/index.jsx
  front-end/src/pages/index.js
Labels: :writing_hand: Feature :writing_hand:

#318 [MAIN-GROUP-11][REQ-40]
  back-end/src/routes/userRouter.js
  front-end/src/helpers/validRegister.js
  front-end/src/pages/Administrator/Management/index.jsx
Labels: :writing_hand: Feature :writing_hand:

#293 [Main group 12] [Customer / Seller Orders]
  back-end/package-lock.json
  back-end/src/controllers/checkoutController.js
  back-end/src/controllers/loginController.js
  back-end/src/controllers/userController.js
  back-end/src/database/seeders/20211109215319-User.js
  back-end/src/database/seeders/20211109215510-Sale.js
  back-end/src/middleware/validateJWT.js
  back-end/src/routers/Customer.js
  back-end/src/routers/Seller.js
  back-end/src/services/checkoutService.js
  back-end/src/services/productService.js
  back-end/src/services/userService.js
  front-end/package-lock.json
  front-end/src/App.jsx
  front-end/src/components/CardMeusPedidos.jsx
  front-end/src/components/DetailsAddress.jsx
  front-end/src/components/ListCheckoutProdutos.jsx
  front-end/src/components/Navbar.jsx
  front-end/src/context/Provider.js
  front-end/src/pages/Checkout.jsx
  front-end/src/pages/Login.jsx
  front-end/src/pages/MeusPedidos.jsx
  front-end/src/pages/OrderDetails.jsx
  front-end/src/pages/Produtos.jsx
  front-end/src/pages/Register.jsx
  front-end/src/services/apis/getAllSellers.js
  front-end/src/services/apis/getCustomer.js
  front-end/src/services/apis/servicesLogin.js
  front-end/src/services/apis/servicesSales.js
  front-end/src/styles/MeusPedidos.js
  front-end/src/styles/Table.js
  package-lock.json
Labels: code review :mag_right:

#235 [main-group-3] - teq 17 checkout tela
  front-end/src/components/ListItemCheckout.js
  front-end/src/components/ListProducts.js
  front-end/src/pages/Checkout.js
  front-end/src/services/api.js
Labels: code review :mag_right:

#84 [MAIN GROUP 6] [Customer Checkout]
  back-end/package-lock.json
  back-end/src/api/Controllers/saleController.js
  back-end/src/api/Controllers/userController.js
  back-end/src/api/Middlewares/validarTokenMiddlewares.js
  back-end/src/api/Services/loginService.js
  back-end/src/api/Services/saleService.js
  back-end/src/api/Services/userService.js
  back-end/src/api/app.js
  back-end/src/api/jwt/jwtValidation.js
  back-end/src/api/routes/login.js
  back-end/src/api/routes/sale.js
  back-end/src/api/routes/user.js
  back-end/src/database/migrations/20211109193531-sales.js
  back-end/src/database/models/sale.js
  back-end/src/database/models/salesProduct.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.jsx
  front-end/src/components/CardOrder.jsx
  front-end/src/components/Checkout/DeliveryDetails.jsx
  front-end/src/components/Checkout/InputText.jsx
  front-end/src/components/Checkout/ItemRow.jsx
  front-end/src/components/Checkout/OrderItemsTable.jsx
  front-end/src/components/Checkout/SellersSelect.jsx
  front-end/src/components/Checkout/TableHeader.jsx
  front-end/src/components/Login.jsx
  front-end/src/pages/Checkout.jsx
  front-end/src/pages/MyOrders.jsx
  front-end/src/pages/OrderDetails.jsx
  front-end/src/styles/Checkout.css
Labels: :writing_hand: In-Development :writing_hand:

#354 [MAIN GROUP 6] [Header customizado e correção req 15]
  front-end/src/components/Header.jsx
  front-end/src/components/ShoppingCart.jsx
  front-end/src/pages/Checkout.jsx
  front-end/src/pages/MyOrders.jsx
  front-end/src/pages/Products.jsx
  front-end/src/styles/Header.css
Labels: code review :mag_right:

#360 [ Main Group 15 ] [ Feature ] [ Front ] [ Register ]
  front-end/package-lock.json
  front-end/src/App.js
  front-end/src/Context/AppProvider.js
  front-end/src/pages/Login.js
  front-end/src/pages/Register.js
Labels: code review :mag_right:, under development

#359 [MAIN GROUP 6] [Sale endpoints]
  back-end/src/api/Controllers/saleController.js
  back-end/src/api/Services/saleService.js
  back-end/src/api/routes/sale.js
  back-end/src/database/models/salesProduct.js
Labels: code review :mag_right:

#404 fix
  front-end/package-lock.json
  front-end/package.json
  front-end/public/index.html
  front-end/src/App.js
  front-end/src/components/DeliveryForm.jsx
  front-end/src/components/ProductsTable.jsx
  front-end/src/pages/AdminManage.jsx
  front-end/src/pages/Checkout.jsx
  front-end/src/pages/CustomerOrders.jsx
  front-end/src/pages/Login.jsx
  front-end/src/pages/Products.jsx
  front-end/src/pages/Register.jsx
  front-end/src/pages/SellerOrder.jsx
Labels: code review :mag_right:

#407 [Main-Group-11][Req-42]
  __tests__/config/matchers/puppeteer/toWaitReqFinished.js
  back-end/src/middlewares/auth/tokenJWT.js
  back-end/src/routes/userRouter.js
  data-testids.md
  front-end/src/pages/Administrator/Management/index.jsx
  front-end/src/services/register/apiRequestAdmin.js
Labels: :writing_hand: In-Development :writing_hand:

#419 [MAIN-GROUP-11][REQ 43]
  __tests__/end-to-end/11admin_manage_users.test.js
  front-end/src/components/TableUsers/index.jsx
  front-end/src/components/TableUsers/style.js
  front-end/src/pages/Administrator/Management/index.jsx
Labels: :writing_hand: Feature :writing_hand:

#409 [MAIN GROUP 6] [Seller order details]
  __tests__/config/matchers/puppeteer/toWaitReqFinished.js
  back-end/package-lock.json
  back-end/src/api/Controllers/loginController.js
  data-testids.md
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.jsx
  front-end/src/components/SellerOrderDetails/ItemRow.jsx
  front-end/src/components/SellerOrderDetails/SaleProducts.jsx
  front-end/src/components/SellerOrderDetails/StatusControllers.jsx
  front-end/src/components/SellerOrderDetails/TableHeader.jsx
  front-end/src/pages/SellerOrderDetails.jsx
  front-end/src/services/sellerEndpoints.js
  front-end/src/styles/SellerOrderDetails.css
Labels: :writing_hand: In-Development :writing_hand:

#423 [Main group 5] [feat] [products screen]
  back-end/images/antarctica_pilsen_300ml.jpg
  back-end/images/becks_330ml.jpg
  back-end/images/becks_600ml.jpg
  back-end/images/brahma_600ml.jpg
  back-end/images/brahma_duplo_malte_350ml.jpg
  back-end/images/da_mantiqueira_red_ale.jpg
  back-end/images/heineken_600ml.jpg
  back-end/images/skol_269ml.jpg
  back-end/images/skol_beats_senses_269ml.jpg
  back-end/images/skol_beats_senses_313ml.jpg
  back-end/images/skol_lata_350ml.jpg
  back-end/images/stella_artois_275ml.jpg
  back-end/public/.gitkeep
  back-end/public/images.zip
  back-end/public/images/antarctica_pilsen_300ml.jpg
  back-end/public/images/becks_330ml.jpg
  back-end/public/images/becks_600ml.jpg
  back-end/public/images/brahma_600ml.jpg
  back-end/public/images/brahma_duplo_malte_350ml.jpg
  back-end/public/images/da_mantiqueira_red_ale.jpg
  back-end/public/images/heineken_600ml.jpg
  back-end/public/images/skol_269ml.jpg
  back-end/public/images/skol_beats_senses_269ml.jpg
  back-end/public/images/skol_beats_senses_313ml.jpg
  back-end/public/images/skol_lata_350ml.jpg
  back-end/public/images/stella_artois_275ml.jpg
  back-end/src/api/app.js
  back-end/src/database/controllers/Login.js
  back-end/src/database/controllers/productControllers.js
  back-end/src/database/middleware/tokenGeneration.js
  back-end/src/database/services/Login.js
  back-end/src/database/services/productServices.js
  front-end/src/components/Navbar/navbarClientComponent.jsx
  front-end/src/components/products/buttonItens.jsx
  front-end/src/components/products/productsComponent.jsx
  front-end/src/pages/customer/products.jsx
  front-end/src/pages/login.jsx
  front-end/src/styles/formRegister.css
  front-end/src/styles/listProducts.css
  front-end/src/styles/navBarClient.css
Labels: :writing_hand: In-Development :writing_hand:

#454 fix - finalizando requisito 25
  __tests__/end-to-end/06customer_order_details.test.js
  front-end/src/components/sellerNavBar/index.jsx
  front-end/src/pages/Client/Details/index.jsx
Labels: :writing_hand: Feature :writing_hand:

#461 Main group 11 req 26
  __tests__/end-to-end/06customer_order_details.test.js
  front-end/src/components/sellerNavBar/index.jsx
  front-end/src/pages/Client/Details/index.jsx
Labels: bug

#425 [ Main Group 2 ] [ Front ] [ Feature ] [ Req 15 ]
  front-end/src/components/Card.jsx
  front-end/src/components/CardList.jsx
Labels: :writing_hand: In-Development :writing_hand:, :writing_hand: Feature :writing_hand:

#494 [Main group 12] [Produtos Style]
  front-end/package-lock.json
  front-end/src/App.css
  front-end/src/components/CardMeusPedidos.jsx
  front-end/src/components/ListUserAdmin.jsx
  front-end/src/components/ManegerUserAdmin.jsx
  front-end/src/pages/Admin.jsx
  front-end/src/styles/Admin.js
  front-end/src/styles/MeusPedidos.js
  front-end/src/styles/Produtos.js
  package-lock.json
Labels: code review :mag_right:
